name: virreport
channels:
  - bioconda
  - conda-forge

dependencies:
## conda-forge packages
  - conda-forge::biopython=1.79
  - conda-forge::matplotlib=2.2.3
  - conda-forge::numpy=1.16.5
  - conda-forge::openjdk=11.0.9.1
  - conda-forge::pandas=1.1.5
  - conda-forge::libwebp=0.5.2
  - conda-forge::pigz=2.6

## bioconda packages
  - bioconda::bcftools=1.12
  - bioconda::bedtools=2.30.0
  - bioconda::blast=2.11.0
  - bioconda::bowtie=1.3.0
  - bioconda::cap3=10.2011
  - bioconda::cutadapt=3.5
  - bioconda::emboss=6.6.0
  - bioconda::fastp=0.20.1
  - bioconda::fastqc=0.11.9
  - bioconda::picard=2.25.6
  - bioconda::samtools=1.12
  - bioconda::spades=3.14.0
  - bioconda::umi_tools=1.1.2
  - bioconda::velvet=1.2.10
  - bioconda::perl-bioperl=1.7.2
